package add.your.package.here;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;

import org.json.JSONArray;
import org.json.JSONObject;

/**
* Util class for fetching a german or english synonym for aa word or expression*
 * English: Powered by the datamuse API
 * German: Powered by openthesaurus
 * Usage: See main methode of this class
* @author lkoeble 21487 && Code partialy generated by ChatGPT (AI)
*/
public class MultiLangSynonymFetcher {

    private static final String EN_API = "https://api.datamuse.com/words?rel_syn=";

    private static final String DE_API =
            "https://www.openthesaurus.de/synonyme/search?q=%s&format=application/json";

    public enum Language { ENGLISH, GERMAN }

    /**
     * Test methode for showcasing usage
     * @param argv not implemented
     */
    public static void main(String[] argv)
    {
        // We fetch the german and english synonyms for the word gehen (go)
        System.out.println("======================================================================");
        System.out.println("We fetch the german and english synonyms for the word essen (eat)");
        System.out.println("======================================================================");
        String[] german = MultiLangSynonymFetcher.getSynonyms("essen", Language.GERMAN, 10);
        String[] english = MultiLangSynonymFetcher.getSynonyms("eat", Language.ENGLISH, 10);
        System.out.println("== GERMAN ==");
        for (String s : german) System.out.print(s + ", ");
        System.out.println("\n== ENGLISH ==");
        for (String s : english) System.out.print(s + ", ");

        // We fetch the synonym to a expression
        System.out.println("\n\n======================================================================");
        System.out.println("We fetch the german and english synonyms for the word ich glaub mein Schwein pfeift");
        System.out.println("======================================================================");
        german = MultiLangSynonymFetcher.getSynonyms("ich glaub mein Schwein pfeift", Language.GERMAN, 10);
        System.out.println("== GERMAN ==");
        for (String s : german) System.out.print(s + ", ");
        System.out.println("\n== ENGLISH ==");
        System.out.print("Doesn't support more than one word");
    }

    /**
     * Get an array of synonyms for a word or expression, in the specified language
     * @param word The word
     * @param lang The language
     * @param limit Max amount of synonyms to return (use -1 if you want all of them)
     * @return Hopefully an array of synonyms (or a bunch of bugs, this hasn't been testet properly, sorry....)
     */
    public static String[] getSynonyms(String word, Language lang, int limit) {
        try {
            String query = URLEncoder.encode(word, StandardCharsets.UTF_8);
            String apiUrl = (lang == Language.ENGLISH) ?
                    EN_API + query :
                    String.format(DE_API, query);

            URL url = new URL(apiUrl);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");

            conn.setRequestProperty("User-Agent", "Mozilla/5.0");

            BufferedReader reader = new BufferedReader(
                    new InputStreamReader(conn.getInputStream(), StandardCharsets.UTF_8)
            );

            StringBuilder result = new StringBuilder();
            String line;

            while ((line = reader.readLine()) != null) {
                result.append(line);
            }
            reader.close();

            String json = result.toString();

            if (json.trim().startsWith("<")) {
                System.err.println("Received HTML instead of JSON for " + word);
                return new String[0];
            }

            String[] resp = parseResponse(json, lang);

            if (limit > 0) return Arrays.copyOf(resp, Math.min(resp.length, limit));
            else return resp;

        } catch (Exception e) {
            System.err.println("Error fetching synonyms: " + e.getMessage());
            return new String[0];
        }
    }

    /**
     * Parse a json response into a list of Synonyms
     * @param json The json (from the server)
     * @param lang The language for the synonyms
     * @return Hopefully an array of synonyms (or a bunch of bugs, this hasn't been testet properly, sorry....)
     */
    private static String[] parseResponse(String json, Language lang) {

        if (lang == Language.ENGLISH) {
            JSONArray arr = new JSONArray(json);
            String[] out = new String[arr.length()];
            for (int i = 0; i < arr.length(); i++) {
                out[i] = arr.getJSONObject(i).getString("word");
            }
            return out;
        } else {
            JSONObject obj = new JSONObject(json);

            if (!obj.has("synsets")) {
                return new String[0];
            }

            JSONArray synsets = obj.getJSONArray("synsets");

            int count = 0;
            for (int i = 0; i < synsets.length(); i++) {
                count += synsets.getJSONObject(i).getJSONArray("terms").length();
            }

            String[] out = new String[count];
            int idx = 0;

            for (int i = 0; i < synsets.length(); i++) {
                JSONArray terms = synsets.getJSONObject(i).getJSONArray("terms");
                for (int j = 0; j < terms.length(); j++) {
                    out[idx++] = terms.getJSONObject(j).getString("term");
                }
            }

            return out;
        }
    }
}

